language: go
go:
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - curl -sLOf https://raw.githubusercontent.com/rafecolton/fmtpolice/master/coverage
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - go test ./...
  - bash coverage
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci
